name: Render Trigger

on:
  push:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check commits for [render] and send HTTP
        run: |
          TRIGGER=false
          # Loop through all commits in the push
          for msg in $(jq -r '.commits[].message' "$GITHUB_EVENT_PATH"); do
            if [[ "$msg" == *"[render]"* ]]; then
              TRIGGER=true
              break
            fi
          done

          if [ "$TRIGGER" = true ]; then
            echo "Triggering HTTP request..."
            curl -X POST https://api.render.com/deploy/srv-d1vcbfruibrs7399a6hg?key=S4So0UPj34Q
          else
            echo "No [render] in commit messages, skipping."
          fi
        shell: bash
