name: Render Trigger

on:
  push:

jobs:
  Trigger_Render:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP if [render] in any commit
        run: |
          # Loop through commits in the push
          TRIGGER=false
          for msg in "${{ github.event.commits[*].message }}"; do
            if [[ "$msg" == *"[render]"* ]]; then
              TRIGGER=true
              break
            fi
          done

          if [ "$TRIGGER" = true ]; then
            echo "Triggering HTTP request..."
            curl -X POST https://your-url.com/trigger
          else
            echo "No [render] in commit messages, skipping."
          fi
