name: Render Trigger

on:
  push:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit messages for [render]
        id: check
        run: |
          # Check if any commit message contains [render]
          if git log -1 --pretty=%B | grep -q "\[render\]"; then
            echo "trigger=true" >> $GITHUB_OUTPUT
          else
            echo "trigger=false" >> $GITHUB_OUTPUT
          fi

      - name: HTTP Request
        if: steps.check.outputs.trigger == 'true'
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1vcbfruibrs7399a6hg?key=S4So0UPj34Q
