name: Render Trigger

on:
  push:

jobs:
  render:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo so we have git info
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Check commit messages for [render]
      - name: Check commit messages
        id: check
        run: |
          # Look at all commits in this push
          TRIGGER=false
          for msg in $(git log origin/main..HEAD --pretty=%B); do
            if [[ "$msg" == *"[render]"* ]]; then
              TRIGGER=true
              break
            fi
          done
          echo "trigger=$TRIGGER" >> $GITHUB_OUTPUT

      # 3. Send HTTP request if triggered
      - name: HTTP Request
        if: steps.check.outputs.trigger == 'true'
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1vcbfruibrs7399a6hg?key=S4So0UPj34Q
